language: go

go:
  - 1.5.2
  - tip

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -f docker-compose-db.yml up -d

install:
  - go get github.com/tools/godep
  - godep version
  - godep restore

script:
  - make test
